import { AlertTriangle, ArrowLeft, ChevronDown, CircleHelp, Plus, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import { MarkdownContent } from '@/components/shared/MarkdownContent';
import { SimulationStatusBadge } from '@/components/shared/SimulationStatusBadge';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { Spinner } from '@/components/ui/spinner';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { MarkdownEditorField } from '@/features/simulations/components/MarkdownEditorField';
import { SimulationPathCard } from '@/features/simulations/components/SimulationPathCard';
import {
  SimulationSummaryLauncher,
  SimulationSummaryRail,
} from '@/features/simulations/components/SimulationSummaryPanel';
import { SimulationTypeBadge } from '@/features/simulations/components/SimulationTypeBadge';
import { cn } from '@/lib/utils';
import type {
  ArtifactIn,
  ArtifactKind,
  ExternalLinkIn,
  ExternalLinkKind,
  ExternalLinkOut,
  SimulationEditableField,
  SimulationOut,
  SimulationStatusValue,
  SimulationSummaryResponseOut,
  SimulationTypeValue,
  SimulationUpdate,
} from '@/types';
import { SIMULATION_EDITABLE_FIELDS } from '@/types';
import { getArtifactsByKind } from '@/types/artifact';
import { formatDate, getSimulationDuration } from '@/utils/utils';

// -------------------- Types --------------------
interface SimulationDetailsViewProps {
  simulation: SimulationOut;
  isCompareSelected?: boolean;
  compareSelectionCount?: number;
  maxCompareSelection?: number;
  canEdit?: boolean;
  isAuthenticated?: boolean;
  isSaving?: boolean;
  saveError?: SimulationSaveError | null;
  backHref?: string;
  backLabel?: string;
  paceLink?: {
    href: string;
    label: string;
  } | null;
  onToggleCompare?: () => void;
  onSave?: (payload: SimulationUpdate) => Promise<boolean> | boolean;
  onClearSaveError?: () => void;
  onLoginToEdit?: () => void;
  isResolvingPace?: boolean;
  showPaceFallbackInfo?: boolean;
  summary?: SimulationSummaryResponseOut | null;
  summaryLoading?: boolean;
  summaryError?: string | null;
  summaryRequested?: boolean;
  summaryElapsedMs?: number;
  summaryLastDurationMs?: number | null;
  onGenerateSummary?: () => void | Promise<void>;
  canGenerateSummary?: boolean;
  llmSummaryAvailable?: boolean;
  autoGenerateDeterministicOnLoad?: boolean;
  showLoginForAiSummary?: boolean;
  isCheckingAuth?: boolean;
  onLoginForSummary?: () => void;
}

export interface SimulationSaveError {
  message: string;
  validationDetails: Array<{
    loc: Array<string | number>;
    msg: string;
  }>;
}

// -------------------- Small UI helpers --------------------
const FieldRow = ({ label, children }: { label: string; children: React.ReactNode }) => (
  <div className="grid grid-cols-12 items-center gap-2">
    <Label className="col-span-3 md:col-span-2 text-xs text-muted-foreground">{label}</Label>
    <div className="col-span-9 min-w-0 md:col-span-10">{children}</div>
  </div>
);

const ReadonlyInput = ({ value, className }: { value?: string | null; className?: string }) => (
  <div
    className={cn(
      'flex min-h-8 min-w-0 items-center truncate rounded-md border border-border/60 bg-muted/35 px-3 py-1.5 text-sm text-foreground/90',
      className,
    )}
    title={value ?? undefined}
  >
    {value || '—'}
  </div>
);

const ReadonlyText = ({ value, className }: { value?: string | null; className?: string }) => (
  <p
    className={cn('min-w-0 truncate text-sm text-foreground/90', className)}
    title={value ?? undefined}
  >
    {value || '—'}
  </p>
);

const UserDisplay = ({
  user,
  fallbackId,
}: {
  user?: { full_name?: string | null; email: string } | null;
  fallbackId?: string | null;
}) => {
  if (user) return <span className="text-sm">by {user.full_name ?? user.email}</span>;
  if (fallbackId) return <span className="text-sm">by {fallbackId}</span>;
  return null;
};

type ResourceKindOption<TKind extends string> = {
  value: TKind;
  label: string;
};

type EditableArtifactRow = {
  kind: ArtifactKind;
  label: string;
  value: string;
};

type EditableLinkRow = {
  kind: ExternalLinkKind;
  label: string;
  value: string;
};

type EditableResourceField = 'kind' | 'label' | 'value';

type ResourceRowFieldErrors = Partial<Record<EditableResourceField, string>>;

type ResourceRowErrorsState = {
  artifacts: ResourceRowFieldErrors[];
  links: ResourceRowFieldErrors[];
};

const ARTIFACT_KIND_OPTIONS: ReadonlyArray<ResourceKindOption<ArtifactKind>> = [
  { value: 'output', label: 'Output' },
  { value: 'archive', label: 'Archive' },
  { value: 'run_script', label: 'Run Script' },
  { value: 'postprocessing_script', label: 'Post-processing Script' },
];

const EXTERNAL_LINK_KIND_OPTIONS: ReadonlyArray<ResourceKindOption<ExternalLinkKind>> = [
  { value: 'diagnostic', label: 'Diagnostic' },
  { value: 'performance', label: 'Performance' },
  { value: 'docs', label: 'Docs' },
  { value: 'other', label: 'Other' },
];

const toEditableArtifactRows = (simulation: SimulationOut): EditableArtifactRow[] =>
  simulation.artifacts.map((artifact) => ({
    kind: artifact.kind,
    label: artifact.label ?? '',
    value: artifact.uri,
  }));

const toEditableLinkRows = (simulation: SimulationOut): EditableLinkRow[] =>
  simulation.links
    .filter((link) => link.ownerType === 'simulation')
    .map((link) => ({
      kind: link.kind,
      label: link.label ?? '',
      value: link.url,
    }));

const toInheritedCaseLinks = (simulation: SimulationOut) =>
  simulation.links.filter((link) => link.ownerType === 'case');

const formatLinkKindLabel = (kind: ExternalLinkKind): string =>
  EXTERNAL_LINK_KIND_OPTIONS.find((option) => option.value === kind)?.label ?? kind;

const groupLinksByKind = (links: ExternalLinkOut[]): Record<ExternalLinkKind, ExternalLinkOut[]> => ({
  diagnostic: links.filter((link) => link.kind === 'diagnostic'),
  performance: links.filter((link) => link.kind === 'performance'),
  docs: links.filter((link) => link.kind === 'docs'),
  other: links.filter((link) => link.kind === 'other'),
});

type ExternalResourceSource = 'simulation' | 'case' | 'derived';

const EXTERNAL_RESOURCE_SOURCE_LABELS: Record<ExternalResourceSource, string> = {
  simulation: 'Simulation',
  case: 'Case',
  derived: 'Derived',
};

const ExternalResourceSourceBadge = ({ source }: { source: ExternalResourceSource }) => (
  <span className="rounded-full border border-border/70 px-2 py-0.5 text-[11px] uppercase tracking-wide text-muted-foreground">
    {EXTERNAL_RESOURCE_SOURCE_LABELS[source]}
  </span>
);

const ExternalResourceLinkRow = ({
  href,
  label,
  source,
  auxiliary,
}: {
  href: string;
  label: string;
  source: ExternalResourceSource;
  auxiliary?: React.ReactNode;
}) => (
  <li className="flex flex-wrap items-start justify-between gap-3 px-4 py-3 text-sm">
    <div className="min-w-0 flex-1">
      <a
        className="font-medium text-blue-600 hover:underline"
        href={href}
        target="_blank"
        rel="noreferrer"
        title={href}
      >
        {label}
      </a>
      {label !== href ? <div className="mt-0.5 break-all text-xs text-muted-foreground">{href}</div> : null}
    </div>
    <div className="flex shrink-0 items-center gap-2">
      <ExternalResourceSourceBadge source={source} />
      {auxiliary}
    </div>
  </li>
);

const ExternalResourceLegend = () => (
  <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-muted-foreground">
    <div className="flex items-center gap-2">
      <ExternalResourceSourceBadge source="simulation" />
      <span>saved on this run</span>
    </div>
    <div className="flex items-center gap-2">
      <ExternalResourceSourceBadge source="case" />
      <span>inherited from case</span>
    </div>
    <div className="flex items-center gap-2">
      <ExternalResourceSourceBadge source="derived" />
      <span>generated for convenience</span>
    </div>
  </div>
);

const ExternalResourceGroup = ({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) => {
  return (
    <div className="border-t first:border-t-0">
      <div className="bg-muted/20 px-4 py-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        {title}
      </div>
      <ul className="divide-y">{children}</ul>
    </div>
  );
};

const normalizeOptionalText = (value: string): string | null => {
  const trimmed = value.trim();
  return trimmed || null;
};

const normalizeArtifactRows = (rows: EditableArtifactRow[]): ArtifactIn[] =>
  rows.map((row) => ({
    kind: row.kind,
    uri: row.value.trim(),
    label: normalizeOptionalText(row.label),
  }));

const normalizeLinkRows = (rows: EditableLinkRow[]): ExternalLinkIn[] =>
  rows.map((row) => ({
    kind: row.kind,
    url: row.value.trim(),
    label: normalizeOptionalText(row.label),
  }));

const createEmptyRowErrors = (count: number): ResourceRowFieldErrors[] =>
  Array.from({ length: count }, () => ({}));

const getClientResourceRowErrors = (
  artifactRows: EditableArtifactRow[],
  linkRows: EditableLinkRow[],
): ResourceRowErrorsState => ({
  artifacts: artifactRows.map((row) =>
    row.value.trim().length === 0 ? { value: 'Artifact URI is required.' } : {},
  ),
  links: linkRows.map((row) =>
    row.value.trim().length === 0 ? { value: 'Link URL is required.' } : {},
  ),
});

const normalizeValidationLoc = (loc: Array<string | number>): Array<string | number> =>
  loc[0] === 'body' ? loc.slice(1) : loc;

const toEditableField = (field: string): EditableResourceField | null => {
  if (field === 'url' || field === 'uri') {
    return 'value';
  }

  if (field === 'kind' || field === 'label') {
    return field;
  }

  return null;
};

const toValidationPathLabel = (loc: Array<string | number>): string => {
  const normalizedLoc = normalizeValidationLoc(loc);
  if (normalizedLoc.length === 0) {
    return 'Validation error';
  }

  return normalizedLoc
    .map((segment) => (typeof segment === 'number' ? `${segment + 1}` : segment))
    .join(' > ');
};

const mapSaveValidationErrors = (
  validationDetails: SimulationSaveError['validationDetails'],
  artifactCount: number,
  linkCount: number,
) => {
  const rowErrors: ResourceRowErrorsState = {
    artifacts: createEmptyRowErrors(artifactCount),
    links: createEmptyRowErrors(linkCount),
  };
  const unmappedMessages: string[] = [];
  let hasMappedLinkValueError = false;

  for (const detail of validationDetails) {
    const loc = normalizeValidationLoc(detail.loc);
    const [resourceName, rowIndex, fieldName] = loc;

    if (
      resourceName === 'artifacts' &&
      typeof rowIndex === 'number' &&
      rowIndex >= 0 &&
      rowIndex < artifactCount &&
      typeof fieldName === 'string'
    ) {
      const field = toEditableField(fieldName);
      if (field) {
        rowErrors.artifacts[rowIndex] = {
          ...rowErrors.artifacts[rowIndex],
          [field]: detail.msg,
        };
        continue;
      }
    }

    if (
      resourceName === 'links' &&
      typeof rowIndex === 'number' &&
      rowIndex >= 0 &&
      rowIndex < linkCount &&
      typeof fieldName === 'string'
    ) {
      const field = toEditableField(fieldName);
      if (field) {
        rowErrors.links[rowIndex] = {
          ...rowErrors.links[rowIndex],
          [field]: detail.msg,
        };
        hasMappedLinkValueError ||= field === 'value';
        continue;
      }
    }

    unmappedMessages.push(`${toValidationPathLabel(detail.loc)}: ${detail.msg}`);
  }

  return {
    rowErrors,
    unmappedMessages,
    hasMappedLinkValueError,
  };
};

const areResourceListsEqual = (left: unknown, right: unknown): boolean =>
  JSON.stringify(left) === JSON.stringify(right);

const mergeRowFieldErrors = (
  primary: ResourceRowFieldErrors,
  secondary: ResourceRowFieldErrors,
): ResourceRowFieldErrors => ({
  ...primary,
  ...secondary,
});

const hasAnyRowErrors = (rowErrors: ResourceRowErrorsState): boolean =>
  [...rowErrors.artifacts, ...rowErrors.links].some((row) => Object.keys(row).length > 0);

const EditableResourceList = <TKind extends string>({
  title,
  description,
  items,
  kindOptions,
  valueLabel,
  valuePlaceholder,
  addLabel,
  onAdd,
  onKindChange,
  onLabelChange,
  onValueChange,
  onRemove,
  rowErrors,
}: {
  title: string;
  description?: string;
  items: Array<{ kind: TKind; label: string; value: string }>;
  kindOptions: ReadonlyArray<ResourceKindOption<TKind>>;
  valueLabel: string;
  valuePlaceholder: string;
  addLabel: string;
  onAdd: () => void;
  onKindChange: (index: number, kind: TKind) => void;
  onLabelChange: (index: number, value: string) => void;
  onValueChange: (index: number, value: string) => void;
  onRemove: (index: number) => void;
  rowErrors?: ResourceRowFieldErrors[];
}) => (
  <div className="space-y-3">
    <div className="flex items-start justify-between gap-3">
      <div>
        <Label className="text-sm font-medium">{title}</Label>
        {description ? <p className="mt-1 text-xs text-muted-foreground">{description}</p> : null}
      </div>
      <Button type="button" variant="outline" size="sm" onClick={onAdd}>
        <Plus className="mr-1 h-4 w-4" />
        {addLabel}
      </Button>
    </div>

    {items.length === 0 ? (
      <div className="rounded-md border border-dashed px-3 py-4 text-sm text-muted-foreground">
        No entries yet.
      </div>
    ) : (
      <div className="space-y-3">
        {items.map((item, index) => (
          <div key={`${item.kind}-${index}`} className="rounded-md border p-3">
            <div className="grid gap-3 md:grid-cols-[160px_minmax(0,1fr)_minmax(0,1.4fr)_auto] md:items-start">
              <div className="space-y-1">
                <Label className="mb-1 block text-xs text-muted-foreground">Kind</Label>
                <Select
                  value={item.kind}
                  onValueChange={(value: TKind) => onKindChange(index, value)}
                >
                  <SelectTrigger className="h-9 text-sm">
                    <SelectValue placeholder="Select kind" />
                  </SelectTrigger>
                  <SelectContent>
                    {kindOptions.map((option) => (
                      <SelectItem key={option.value} value={option.value}>
                        {option.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <div className="min-h-4" aria-hidden="true" />
              </div>
              <div className="space-y-1">
                <Label className="mb-1 block text-xs text-muted-foreground">Label</Label>
                <Input
                  value={item.label}
                  onChange={(event) => onLabelChange(index, event.target.value)}
                  placeholder="Optional label"
                  className={cn(
                    'h-9 text-sm',
                    rowErrors?.[index]?.label ? 'border-red-300 focus-visible:ring-red-200' : '',
                  )}
                />
                {rowErrors?.[index]?.label ? (
                  <p className="min-h-4 text-xs leading-4 text-red-600">{rowErrors[index].label}</p>
                ) : (
                  <div className="min-h-4" aria-hidden="true" />
                )}
              </div>
              <div className="space-y-1">
                <Label className="mb-1 block text-xs text-muted-foreground">{valueLabel}</Label>
                <Input
                  value={item.value}
                  onChange={(event) => onValueChange(index, event.target.value)}
                  placeholder={valuePlaceholder}
                  className={cn(
                    'h-9 text-sm',
                    rowErrors?.[index]?.value ? 'border-red-300 focus-visible:ring-red-200' : '',
                  )}
                />
                {rowErrors?.[index]?.value ? (
                  <p className="min-h-4 text-xs leading-4 text-red-600">{rowErrors[index].value}</p>
                ) : (
                  <div className="min-h-4" aria-hidden="true" />
                )}
              </div>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                onClick={() => onRemove(index)}
                aria-label={`Remove ${title} item ${index + 1}`}
                className="mt-6 self-start"
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          </div>
        ))}
      </div>
    )}
  </div>
);

const EDITABLE_FIELDS = SIMULATION_EDITABLE_FIELDS;

type EditableField = SimulationEditableField;
type EditableFormState = Record<EditableField, string>;

const SINGLE_LINE_FIELDS: ReadonlySet<EditableField> = new Set([
  'simulationType',
  'status',
  'campaign',
  'experimentType',
]);

const SIMULATION_TYPE_OPTIONS: ReadonlyArray<{
  value: SimulationTypeValue;
  label: string;
}> = [
  { value: 'unknown', label: 'Not set' },
  { value: 'production', label: 'Production' },
  { value: 'experimental', label: 'Experimental' },
  { value: 'test', label: 'Test' },
];

const STATUS_OPTIONS: ReadonlyArray<{
  value: SimulationStatusValue;
  label: string;
}> = [
  { value: 'unknown', label: 'Unknown' },
  { value: 'created', label: 'Created' },
  { value: 'queued', label: 'Queued' },
  { value: 'running', label: 'Running' },
  { value: 'failed', label: 'Failed' },
  { value: 'completed', label: 'Completed' },
];

const toEditableFormState = (simulation: SimulationOut): EditableFormState => ({
  simulationType: simulation.simulationType,
  status: simulation.status,
  description: simulation.description ?? '',
  campaign: simulation.campaign ?? '',
  experimentType: simulation.experimentType ?? '',
  keyFeatures: simulation.keyFeatures ?? '',
  knownIssues: simulation.knownIssues ?? '',
  notesMarkdown: simulation.notesMarkdown ?? '',
});

const normalizeEditableValue = (field: EditableField, value: string): string | null => {
  const trimmed = value.trim();

  if (!trimmed) {
    return null;
  }

  return SINGLE_LINE_FIELDS.has(field) ? trimmed : value;
};

const buildUpdatePayload = (
  simulation: SimulationOut,
  formState: EditableFormState,
  artifactRows: EditableArtifactRow[],
  linkRows: EditableLinkRow[],
): SimulationUpdate => {
  const payload: SimulationUpdate = {};
  const mutablePayload = payload as Record<string, string | null>;

  for (const field of EDITABLE_FIELDS) {
    const nextValue = normalizeEditableValue(field, formState[field]);
    const currentValue = simulation[field] ?? null;

    if (nextValue !== currentValue) {
      mutablePayload[field] = nextValue;
    }
  }

  const nextArtifacts = normalizeArtifactRows(artifactRows);
  const currentArtifacts = normalizeArtifactRows(toEditableArtifactRows(simulation));
  if (!areResourceListsEqual(nextArtifacts, currentArtifacts)) {
    payload.artifacts = nextArtifacts;
  }

  const nextLinks = normalizeLinkRows(linkRows);
  const currentLinks = normalizeLinkRows(toEditableLinkRows(simulation));
  if (!areResourceListsEqual(nextLinks, currentLinks)) {
    payload.links = nextLinks;
  }

  return payload;
};

// -------------------- View Component --------------------
export const SimulationDetailsView = ({
  simulation,
  isCompareSelected = false,
  compareSelectionCount: compareSelectionCountProp = 0,
  maxCompareSelection: maxCompareSelectionProp = 5,
  canEdit = false,
  isAuthenticated = false,
  isSaving = false,
  saveError = null,
  backHref = '/browse',
  backLabel = 'Back to Runs',
  paceLink = null,
  onToggleCompare,
  onSave,
  onClearSaveError,
  onLoginToEdit,
  isResolvingPace = false,
  showPaceFallbackInfo = false,
  summary = null,
  summaryLoading = false,
  summaryError = null,
  summaryRequested = false,
  summaryElapsedMs = 0,
  summaryLastDurationMs = null,
  onGenerateSummary,
  canGenerateSummary = false,
  llmSummaryAvailable = false,
  autoGenerateDeterministicOnLoad = false,
  showLoginForAiSummary = false,
  isCheckingAuth = false,
  onLoginForSummary,
}: SimulationDetailsViewProps) => {
  const [activeTab, setActiveTab] = useState('summary');
  const [isEditing, setIsEditing] = useState(false);
  const [isAdvancedMetadataOpen, setIsAdvancedMetadataOpen] = useState(false);
  const [formState, setFormState] = useState<EditableFormState>(() =>
    toEditableFormState(simulation),
  );
  const [artifactRows, setArtifactRows] = useState<EditableArtifactRow[]>(() =>
    toEditableArtifactRows(simulation),
  );
  const [linkRows, setLinkRows] = useState<EditableLinkRow[]>(() => toEditableLinkRows(simulation));
  const [serverRowErrors, setServerRowErrors] = useState<ResourceRowErrorsState>({
    artifacts: [],
    links: [],
  });
  const [saveSummaryMessage, setSaveSummaryMessage] = useState<string | null>(null);
  const inheritedCaseLinks = toInheritedCaseLinks(simulation);
  const simulationOwnedLinks = simulation.links.filter((link) => link.ownerType === 'simulation');
  const groupedSimulationOwnedLinks = groupLinksByKind(simulationOwnedLinks);
  const groupedInheritedCaseLinks = groupLinksByKind(inheritedCaseLinks);
  const externalResourceKinds: ExternalLinkKind[] = ['diagnostic', 'performance', 'docs', 'other'];
  const hasExternalResources =
    externalResourceKinds.some(
      (kind) =>
        groupedSimulationOwnedLinks[kind].length > 0 || groupedInheritedCaseLinks[kind].length > 0,
    ) || Boolean(paceLink);
  const outputArtifacts = getArtifactsByKind(
    simulation.artifacts,
    simulation.groupedArtifacts,
    'output',
  ).map((artifact) => ({
    url: artifact.uri,
    label: artifact.label?.trim() || artifact.uri,
  }));
  const archiveArtifacts = getArtifactsByKind(
    simulation.artifacts,
    simulation.groupedArtifacts,
    'archive',
  ).map((artifact) => ({
    url: artifact.uri,
    label: artifact.label?.trim() || artifact.uri,
  }));
  const runScriptArtifacts = getArtifactsByKind(
    simulation.artifacts,
    simulation.groupedArtifacts,
    'run_script',
  ).map((artifact) => ({
    url: artifact.uri,
    label: artifact.label?.trim() || artifact.uri,
  }));
  const postprocessingScriptArtifacts = getArtifactsByKind(
    simulation.artifacts,
    simulation.groupedArtifacts,
    'postprocessing_script',
  ).map((artifact) => ({
    url: artifact.uri,
    label: artifact.label?.trim() || artifact.uri,
  }));

  // Temporary local-only comments
  const [newComment, setNewComment] = useState('');
  const [comments, setComments] = useState<
    { id: string; author: string; date: string; text: string }[]
  >([
    {
      id: 'c1',
      author: 'Jane Doe',
      date: '2024-02-15T13:45:00Z',
      text: 'The sea-ice diagnostics will be added later.',
    },
  ]);

  useEffect(() => {
    setFormState(toEditableFormState(simulation));
    setArtifactRows(toEditableArtifactRows(simulation));
    setLinkRows(toEditableLinkRows(simulation));
    setIsEditing(false);
  }, [simulation]);

  useEffect(() => {
    if (!canEdit) {
      setFormState(toEditableFormState(simulation));
      setArtifactRows(toEditableArtifactRows(simulation));
      setLinkRows(toEditableLinkRows(simulation));
      setIsEditing(false);
    }
  }, [canEdit, simulation]);

  useEffect(() => {
    if (!saveError) {
      setServerRowErrors({
        artifacts: createEmptyRowErrors(artifactRows.length),
        links: createEmptyRowErrors(linkRows.length),
      });
      setSaveSummaryMessage(null);
      return;
    }

    const mappedErrors = mapSaveValidationErrors(
      saveError.validationDetails,
      artifactRows.length,
      linkRows.length,
    );

    setServerRowErrors(mappedErrors.rowErrors);

    if (mappedErrors.unmappedMessages.length > 0) {
      setSaveSummaryMessage(mappedErrors.unmappedMessages.join(' '));
      return;
    }

    if (mappedErrors.hasMappedLinkValueError) {
      setSaveSummaryMessage('One or more links need a full URL including https://.');
      return;
    }

    if (hasAnyRowErrors(mappedErrors.rowErrors)) {
      setSaveSummaryMessage('Fix highlighted resource rows before saving.');
      return;
    }

    setSaveSummaryMessage(saveError.message);
  }, [artifactRows.length, linkRows.length, saveError]);

  const clientRowErrors = getClientResourceRowErrors(artifactRows, linkRows);
  const combinedRowErrors: ResourceRowErrorsState = {
    artifacts: artifactRows.map((_, index) =>
      mergeRowFieldErrors(
        clientRowErrors.artifacts[index] ?? {},
        serverRowErrors.artifacts[index] ?? {},
      ),
    ),
    links: linkRows.map((_, index) =>
      mergeRowFieldErrors(clientRowErrors.links[index] ?? {}, serverRowErrors.links[index] ?? {}),
    ),
  };
  const hasClientResourceErrors = hasAnyRowErrors(clientRowErrors);
  const summaryErrorMessage = saveSummaryMessage
    ? saveSummaryMessage
    : hasClientResourceErrors
      ? 'Fix highlighted resource rows before saving.'
      : null;

  const updateField = (field: EditableField, value: string) => {
    onClearSaveError?.();
    setFormState((current) => ({
      ...current,
      [field]: value,
    }));
  };

  const handleCancelEdit = () => {
    onClearSaveError?.();
    setFormState(toEditableFormState(simulation));
    setArtifactRows(toEditableArtifactRows(simulation));
    setLinkRows(toEditableLinkRows(simulation));
    setIsEditing(false);
  };

  const handleSave = async () => {
    if (!onSave) return;
    if (hasClientResourceErrors) {
      return;
    }

    const payload = buildUpdatePayload(simulation, formState, artifactRows, linkRows);

    if (Object.keys(payload).length === 0) {
      onClearSaveError?.();
      setIsEditing(false);
      return;
    }

    const saved = await onSave(payload);

    if (saved) {
      setIsEditing(false);
    }
  };

  const hasUnsavedChanges =
    Object.keys(buildUpdatePayload(simulation, formState, artifactRows, linkRows)).length > 0;
  const compareSelectionCount = compareSelectionCountProp ?? 0;
  const maxCompareSelection = maxCompareSelectionProp ?? 5;
  const isCompareActionDisabled =
    !isCompareSelected && compareSelectionCount >= maxCompareSelection;
  const compareActionLabel = isCompareSelected ? 'Remove from Comparison' : 'Add to Comparison';
  const compareActionTooltip = isCompareActionDisabled
    ? `Compare list is full. Remove one of the ${maxCompareSelection} selected runs first.`
    : undefined;
  const editAccessMessage = isAuthenticated
    ? 'Read-only. Editing requires SimBoard admin access or verified E3SM GitHub organization membership.'
    : 'Log in with GitHub to edit simulation metadata.';

  const addComment = () => {
    if (!newComment.trim()) return;
    setComments((prev) => [
      ...prev,
      {
        id: `c${prev.length + 1}`,
        author: 'You',
        date: new Date().toISOString(),
        text: newComment.trim(),
      },
    ]);
    setNewComment('');
  };

  const updateArtifactRow = (index: number, updates: Partial<EditableArtifactRow>) => {
    onClearSaveError?.();
    setArtifactRows((current) =>
      current.map((row, rowIndex) => (rowIndex === index ? { ...row, ...updates } : row)),
    );
  };

  const updateLinkRow = (index: number, updates: Partial<EditableLinkRow>) => {
    onClearSaveError?.();
    setLinkRows((current) =>
      current.map((row, rowIndex) => (rowIndex === index ? { ...row, ...updates } : row)),
    );
  };

  const addArtifactRow = () => {
    onClearSaveError?.();
    setArtifactRows((current) => [...current, { kind: 'output', label: '', value: '' }]);
  };

  const addLinkRow = () => {
    onClearSaveError?.();
    setLinkRows((current) => [...current, { kind: 'diagnostic', label: '', value: '' }]);
  };

  const removeArtifactRow = (index: number) => {
    onClearSaveError?.();
    setArtifactRows((current) => current.filter((_, rowIndex) => rowIndex !== index));
  };

  const removeLinkRow = (index: number) => {
    onClearSaveError?.();
    setLinkRows((current) => current.filter((_, rowIndex) => rowIndex !== index));
  };

  return (
    <div className="mx-auto w-full max-w-[1400px] space-y-6 px-6 py-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <Button variant="outline" size="sm" asChild className="mb-3">
            <Link to={backHref}>
              <ArrowLeft className="h-4 w-4" />
              {backLabel}
            </Link>
          </Button>
          <h1 className="text-2xl font-bold">{simulation.executionId}</h1>
          <p className="text-sm text-muted-foreground">{simulation.caseName}</p>
          <div className="mt-1 flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
            <span>Type:</span>
            <SimulationTypeBadge simulationType={simulation.simulationType} />
            <span>•</span>
            <span>Status:</span>
            <SimulationStatusBadge status={simulation.status} />
            {simulation.gitTag && (
              <>
                <span>•</span>
                <span>Version/Tag:</span>
                <code className="rounded bg-muted px-2 py-0.5 text-xs">{simulation.gitTag}</code>
              </>
            )}
          </div>
        </div>
        <div className="flex items-center gap-2">
          {compareActionTooltip ? (
            <TooltipProvider delayDuration={150}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span tabIndex={0}>
                    <Button
                      variant="outline"
                      onClick={onToggleCompare}
                      disabled={isCompareActionDisabled}
                    >
                      {compareActionLabel}
                    </Button>
                  </span>
                </TooltipTrigger>
                <TooltipContent>{compareActionTooltip}</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ) : (
            <Button variant="outline" onClick={onToggleCompare}>
              {compareActionLabel}
            </Button>
          )}
          {!isEditing &&
            (canEdit ? (
              <Button onClick={() => setIsEditing(true)}>Edit</Button>
            ) : !isAuthenticated ? (
              <Button variant="outline" onClick={onLoginToEdit}>
                Log In to Edit
              </Button>
            ) : (
              <TooltipProvider delayDuration={150}>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span tabIndex={0}>
                      <Button disabled>Edit</Button>
                    </span>
                  </TooltipTrigger>
                  <TooltipContent>{editAccessMessage}</TooltipContent>
                </Tooltip>
              </TooltipProvider>
            ))}
          {canEdit && isEditing && (
            <>
              <Button variant="outline" onClick={handleCancelEdit} disabled={isSaving}>
                Cancel
              </Button>
              <Button
                onClick={handleSave}
                disabled={isSaving || !hasUnsavedChanges || hasClientResourceErrors}
              >
                {isSaving ? 'Saving…' : 'Save Changes'}
              </Button>
            </>
          )}
        </div>
      </div>

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="w-full justify-start overflow-x-auto">
          <TabsTrigger value="summary">Summary</TabsTrigger>
          <TabsTrigger value="outputs">Outputs & Logs</TabsTrigger>
        </TabsList>

        {/* SUMMARY TAB */}
        <TabsContent value="summary" className="space-y-6">
          <div className="xl:hidden">
            <SimulationSummaryLauncher
              summary={summary}
              summaryLoading={summaryLoading}
              summaryError={summaryError}
              summaryRequested={summaryRequested}
              summaryElapsedMs={summaryElapsedMs}
              summaryLastDurationMs={summaryLastDurationMs}
              onGenerateSummary={onGenerateSummary}
              canGenerateSummary={canGenerateSummary}
              llmSummaryAvailable={llmSummaryAvailable}
              autoGenerateDeterministicOnLoad={autoGenerateDeterministicOnLoad}
              showLoginForAiSummary={showLoginForAiSummary}
              isCheckingAuth={isCheckingAuth}
              onLoginForSummary={onLoginForSummary}
            />
          </div>

          <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px] xl:items-start">
            <div className="space-y-6">
              <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Configuration</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <FieldRow label="Case Name">
                      <ReadonlyInput value={simulation.caseName} />
                    </FieldRow>
                    {simulation.caseGroup && (
                      <FieldRow label="Case Group">
                        <ReadonlyInput value={simulation.caseGroup} />
                      </FieldRow>
                    )}
                    <FieldRow label="Case Hash">
                      <ReadonlyInput
                        value={simulation.caseHash ?? undefined}
                        className="font-mono"
                      />
                    </FieldRow>
                    <FieldRow label="Model Version">
                      <ReadonlyInput value={simulation.gitTag ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Compset">
                      <ReadonlyInput value={simulation.compset ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Compset Alias">
                      <ReadonlyInput value={simulation.compsetAlias ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Grid Name">
                      <ReadonlyInput value={simulation.gridName ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Grid Resolution">
                      <ReadonlyInput value={simulation.gridResolution ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Initialization Type">
                      <ReadonlyInput value={simulation.initializationType ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Compiler">
                      <ReadonlyInput value={simulation.compiler ?? undefined} />
                    </FieldRow>
                    {(isEditing || simulation.description) && (
                      <div className="pt-2">
                        {isEditing ? (
                          <MarkdownEditorField
                            label="Description"
                            value={formState.description}
                            onChange={(value) => updateField('description', value)}
                            placeholder="Add description..."
                          />
                        ) : (
                          <>
                            <Label className="mb-1 block text-xs text-muted-foreground">
                              Description
                            </Label>
                            <MarkdownContent content={simulation.description} />
                          </>
                        )}
                      </div>
                    )}
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Model Setup</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <FieldRow label="Simulation Type">
                      {isEditing ? (
                        <Select
                          value={formState.simulationType}
                          onValueChange={(value: SimulationTypeValue) =>
                            updateField('simulationType', value)
                          }
                        >
                          <SelectTrigger className="h-8 text-sm">
                            <SelectValue placeholder="Select simulation type" />
                          </SelectTrigger>
                          <SelectContent>
                            {SIMULATION_TYPE_OPTIONS.map((option) => (
                              <SelectItem key={option.value} value={option.value}>
                                {option.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      ) : (
                        <SimulationTypeBadge simulationType={simulation.simulationType} />
                      )}
                    </FieldRow>
                    <FieldRow label="Status">
                      {isEditing ? (
                        <Select
                          value={formState.status}
                          onValueChange={(value: SimulationStatusValue) =>
                            updateField('status', value)
                          }
                        >
                          <SelectTrigger className="h-8 text-sm">
                            <SelectValue placeholder="Select status" />
                          </SelectTrigger>
                          <SelectContent>
                            {STATUS_OPTIONS.map((option) => (
                              <SelectItem key={option.value} value={option.value}>
                                {option.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      ) : (
                        <SimulationStatusBadge status={simulation.status} />
                      )}
                    </FieldRow>
                    <FieldRow label="Campaign ID">
                      {isEditing ? (
                        <Input
                          value={formState.campaign}
                          onChange={(event) => updateField('campaign', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyInput value={simulation.campaign} />
                      )}
                    </FieldRow>
                    <FieldRow label="Experiment Type ID">
                      {isEditing ? (
                        <Input
                          value={formState.experimentType}
                          onChange={(event) => updateField('experimentType', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyInput value={simulation.experimentType} />
                      )}
                    </FieldRow>
                    <FieldRow label="Machine">
                      <ReadonlyInput value={simulation.machine.name} />
                    </FieldRow>
                  </CardContent>
                </Card>
              </div>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-base">Compare Setup</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <p className="text-sm text-muted-foreground">
                    Use case details to select runs from one Case Hash subgroup, then open compare
                    for side-by-side review.
                  </p>
                  <Button variant="outline" asChild>
                    <Link to={`/cases/${simulation.caseId}`}>Open Case Details</Link>
                  </Button>
                </CardContent>
              </Card>

              <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Timeline</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2">
                    <FieldRow label="Simulation Start Date">
                      <span className="text-sm">
                        {simulation.simulationStartDate
                          ? formatDate(simulation.simulationStartDate)
                          : '—'}
                      </span>
                    </FieldRow>
                    <FieldRow label="Simulation End Date">
                      <span className="text-sm">
                        {simulation.simulationEndDate
                          ? formatDate(simulation.simulationEndDate)
                          : '—'}
                      </span>
                    </FieldRow>
                    <FieldRow label="Total Duration">
                      <span className="text-sm">
                        {simulation.simulationStartDate && simulation.simulationEndDate
                          ? getSimulationDuration(
                              simulation.simulationStartDate,
                              simulation.simulationEndDate,
                            )
                          : '—'}
                      </span>
                    </FieldRow>
                    {simulation.runStartDate && (
                      <FieldRow label="Run Start Date">
                        <span className="text-sm">{formatDate(simulation.runStartDate)}</span>
                      </FieldRow>
                    )}
                    {simulation.runEndDate && (
                      <FieldRow label="Run End Date">
                        <span className="text-sm">{formatDate(simulation.runEndDate)}</span>
                      </FieldRow>
                    )}
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Provenance</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Created:
                      </Label>
                      <span className="text-sm">
                        {simulation.createdAt ? formatDate(simulation.createdAt) : '—'}
                      </span>
                      <UserDisplay
                        user={simulation.createdByUser}
                        fallbackId={simulation.createdBy}
                      />
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Last edited:
                      </Label>
                      <span className="text-sm">
                        {simulation.updatedAt ? formatDate(simulation.updatedAt) : '—'}
                      </span>
                      <UserDisplay
                        user={simulation.lastUpdatedByUser}
                        fallbackId={simulation.lastUpdatedBy}
                      />
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Simulation UUID:
                      </Label>
                      <ReadonlyInput value={simulation.id} />
                      {simulation.id && (
                        <Button
                          variant="outline"
                          size="sm"
                          type="button"
                          onClick={() => navigator.clipboard.writeText(simulation.id)}
                          title="Copy full Simulation ID"
                        >
                          Copy
                        </Button>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Case ID:
                      </Label>
                      <ReadonlyInput value={simulation.caseId} />
                      {simulation.caseId && (
                        <Button
                          variant="outline"
                          size="sm"
                          type="button"
                          onClick={() => navigator.clipboard.writeText(simulation.caseId)}
                          title="Copy full Case ID"
                        >
                          Copy
                        </Button>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Machine ID:
                      </Label>
                      <ReadonlyInput value={simulation.machineId} />
                      {simulation.machineId && (
                        <Button
                          variant="outline"
                          size="sm"
                          type="button"
                          onClick={() => navigator.clipboard.writeText(simulation.machineId)}
                          title="Copy full Machine ID"
                        >
                          Copy
                        </Button>
                      )}
                    </div>

                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Git Repository:
                      </Label>
                      {simulation.gitRepositoryUrl ? (
                        <a
                          href={simulation.gitRepositoryUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="block min-w-0 truncate text-sm text-blue-600 hover:underline"
                          title={simulation.gitRepositoryUrl}
                        >
                          {simulation.gitRepositoryUrl}
                        </a>
                      ) : (
                        <p className="text-sm">—</p>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Git Branch:
                      </Label>
                      <ReadonlyText value={simulation.gitBranch} />
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Git Tag:
                      </Label>
                      <ReadonlyText value={simulation.gitTag} />
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Git Commit Hash:
                      </Label>
                      <ReadonlyText value={simulation.gitCommitHash} />
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        HPC Username:
                      </Label>
                      <ReadonlyText value={simulation.hpcUsername} />
                    </div>
                  </CardContent>
                </Card>
              </div>

              {(isEditing || simulation.keyFeatures || simulation.knownIssues) && (
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Scientific Metadata</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {(isEditing || simulation.keyFeatures) && (
                      <div>
                        {isEditing ? (
                          <MarkdownEditorField
                            label="Key Features"
                            value={formState.keyFeatures}
                            onChange={(value) => updateField('keyFeatures', value)}
                            placeholder="Add key features..."
                          />
                        ) : (
                          <>
                            <Label className="mb-1 block text-xs text-muted-foreground">
                              Key Features
                            </Label>
                            <MarkdownContent content={simulation.keyFeatures} />
                          </>
                        )}
                      </div>
                    )}
                    {(isEditing || simulation.knownIssues) && (
                      <div>
                        {isEditing ? (
                          <MarkdownEditorField
                            label="Known Issues"
                            value={formState.knownIssues}
                            onChange={(value) => updateField('knownIssues', value)}
                            placeholder="Add known issues..."
                          />
                        ) : (
                          <>
                            <Label className="mb-1 block text-xs text-muted-foreground">
                              Known Issues
                            </Label>
                            <MarkdownContent content={simulation.knownIssues} />
                          </>
                        )}
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

              {simulation.extra && Object.keys(simulation.extra).length > 0 && (
                <Collapsible open={isAdvancedMetadataOpen} onOpenChange={setIsAdvancedMetadataOpen}>
                  <Card>
                    <CardHeader className="pb-2">
                      <CollapsibleTrigger className="flex w-full items-center justify-between [&[data-state=open]>svg]:rotate-180">
                        <CardTitle className="text-base">Advanced Metadata</CardTitle>
                        <ChevronDown className="h-4 w-4 text-muted-foreground transition-transform duration-200" />
                      </CollapsibleTrigger>
                    </CardHeader>
                    <CollapsibleContent>
                      <CardContent>
                        {isAdvancedMetadataOpen && (
                          <pre className="max-h-[400px] overflow-auto rounded-md bg-muted p-4 text-xs">
                            {JSON.stringify(simulation.extra, null, 2)}
                          </pre>
                        )}
                      </CardContent>
                    </CollapsibleContent>
                  </Card>
                </Collapsible>
              )}

              <Card>
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-base">External Resources</CardTitle>
                  </div>
                </CardHeader>
                <CardContent>
                  {isEditing ? (
                    <div className="space-y-4">
                      <EditableResourceList
                        title="Simulation-specific external links"
                        description="Add, relabel, or remove links saved directly on this simulation."
                        items={linkRows}
                        kindOptions={EXTERNAL_LINK_KIND_OPTIONS}
                        valueLabel="URL"
                        valuePlaceholder="https://example.com/resource"
                        addLabel="Add link"
                        onAdd={addLinkRow}
                        onKindChange={(index, kind) => updateLinkRow(index, { kind })}
                        onLabelChange={(index, value) => updateLinkRow(index, { label: value })}
                        onValueChange={(index, value) => updateLinkRow(index, { value })}
                        onRemove={removeLinkRow}
                        rowErrors={combinedRowErrors.links}
                      />
                      {inheritedCaseLinks.length ? (
                        <div className="rounded-md border bg-muted/20 px-3 py-3 text-sm">
                          <div className="font-medium">Inherited case links</div>
                          <div className="mt-1 text-muted-foreground">
                            These links come from case-level diagnostics. They stay visible here
                            but are not changed by simulation save.
                          </div>
                          <ul className="mt-3 space-y-2">
                            {inheritedCaseLinks.map((link) => (
                              <li
                                key={link.id}
                                className="flex flex-wrap items-center gap-2 text-sm"
                              >
                                <span className="rounded-full border border-border/70 px-2 py-0.5 text-xs text-muted-foreground">
                                  {formatLinkKindLabel(link.kind)}
                                </span>
                                <a
                                  className="min-w-0 truncate text-blue-600 hover:underline"
                                  href={link.url}
                                  target="_blank"
                                  rel="noreferrer"
                                  title={link.url}
                                >
                                  {link.label || link.url}
                                </a>
                              </li>
                            ))}
                          </ul>
                        </div>
                      ) : null}
                      {paceLink ? (
                        <div className="rounded-md border bg-muted/20 px-3 py-3 text-sm">
                          <div className="font-medium">PACE helper link</div>
                          <div className="mt-1 text-muted-foreground">
                            This derived link is shown for convenience and is not saved with the
                            simulation.
                          </div>
                          <a
                            className="mt-2 inline-flex items-center gap-1 text-blue-600 hover:underline"
                            href={paceLink.href}
                            target="_blank"
                            rel="noreferrer"
                          >
                            {paceLink.label}
                          </a>
                        </div>
                      ) : null}
                    </div>
                  ) : (
                    <>
                      <div className="space-y-4">
                        <ExternalResourceLegend />
                        {hasExternalResources ? (
                          <div className="overflow-hidden rounded-lg border">
                            {externalResourceKinds.map((kind) => {
                              const simulationLinksForKind = groupedSimulationOwnedLinks[kind];
                              const caseLinksForKind = groupedInheritedCaseLinks[kind];
                              const showDerivedPaceLink = kind === 'performance' && Boolean(paceLink);

                              if (
                                simulationLinksForKind.length === 0 &&
                                caseLinksForKind.length === 0 &&
                                !showDerivedPaceLink
                              ) {
                                return null;
                              }

                              return (
                                <ExternalResourceGroup
                                  key={kind}
                                  title={formatLinkKindLabel(kind)}
                                >
                                  {simulationLinksForKind.map((link) => (
                                    <ExternalResourceLinkRow
                                      key={link.id}
                                      href={link.url}
                                      label={link.label || link.url}
                                      source="simulation"
                                    />
                                  ))}
                                  {caseLinksForKind.map((link) => (
                                    <ExternalResourceLinkRow
                                      key={link.id}
                                      href={link.url}
                                      label={link.label || link.url}
                                      source="case"
                                    />
                                  ))}
                                  {showDerivedPaceLink && paceLink ? (
                                    <ExternalResourceLinkRow
                                      href={paceLink.href}
                                      label={paceLink.label}
                                      source="derived"
                                      auxiliary={
                                        <>
                                          {isResolvingPace ? (
                                            <>
                                              <Spinner className="size-3 text-muted-foreground" />
                                              <TooltipProvider delayDuration={150}>
                                                <Tooltip>
                                                  <TooltipTrigger asChild>
                                                    <button
                                                      type="button"
                                                      aria-label="PACE link resolution status"
                                                      className="text-muted-foreground hover:text-foreground"
                                                    >
                                                      <CircleHelp className="size-3" />
                                                    </button>
                                                  </TooltipTrigger>
                                                  <TooltipContent>
                                                    Checking for a direct PACE experiment link
                                                  </TooltipContent>
                                                </Tooltip>
                                              </TooltipProvider>
                                            </>
                                          ) : null}
                                          {!isResolvingPace && showPaceFallbackInfo ? (
                                            <TooltipProvider delayDuration={150}>
                                              <Tooltip>
                                                <TooltipTrigger asChild>
                                                  <button
                                                    type="button"
                                                    aria-label="PACE link fallback information"
                                                    className="text-muted-foreground hover:text-foreground"
                                                  >
                                                    <CircleHelp className="size-3" />
                                                  </button>
                                                </TooltipTrigger>
                                                <TooltipContent>
                                                  Direct PACE experiment link not found. Search
                                                  results may still contain this run.
                                                </TooltipContent>
                                              </Tooltip>
                                            </TooltipProvider>
                                          ) : null}
                                        </>
                                      }
                                    />
                                  ) : null}
                                </ExternalResourceGroup>
                              );
                            })}
                          </div>
                        ) : (
                          <div className="rounded-lg border border-dashed px-4 py-6 text-sm text-muted-foreground">
                            No external resources available yet.
                          </div>
                        )}
                      </div>
                    </>
                  )}
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-base">Notes</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {isEditing ? (
                    <MarkdownEditorField
                      label="Notes"
                      value={formState.notesMarkdown}
                      onChange={(value) => updateField('notesMarkdown', value)}
                      placeholder="Add notes..."
                      minHeightClassName="min-h-[160px]"
                    />
                  ) : (
                    <MarkdownContent content={simulation.notesMarkdown} className="min-h-[160px]" />
                  )}
                  {!canEdit && (
                    <p className="text-xs text-muted-foreground">
                      {isAuthenticated
                        ? 'You are signed in, but this simulation is read-only. Editing requires SimBoard admin access or verified E3SM GitHub organization membership.'
                        : 'Log in with GitHub to edit simulation metadata. This page stays read-only while signed out.'}
                    </p>
                  )}
                  {canEdit && isEditing && (
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-xs text-muted-foreground">
                        Save updates metadata, notes, artifacts, and external links together.
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="outline" onClick={handleCancelEdit} disabled={isSaving}>
                          Cancel
                        </Button>
                        <Button
                          onClick={handleSave}
                          disabled={isSaving || !hasUnsavedChanges || hasClientResourceErrors}
                        >
                          {isSaving ? 'Saving…' : 'Save Changes'}
                        </Button>
                      </div>
                    </div>
                  )}
                  {isEditing && summaryErrorMessage ? (
                    <div className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">
                      <div className="flex items-start gap-2">
                        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
                        <div>
                          <p className="font-medium">Save blocked</p>
                          <p className="mt-1 text-red-700">{summaryErrorMessage}</p>
                        </div>
                      </div>
                    </div>
                  ) : null}
                </CardContent>
              </Card>

              <div>
                <h3 className="mb-2 text-sm font-semibold tracking-tight">Comments</h3>
                <div className="space-y-4">
                  {comments.map((c) => (
                    <div
                      key={c.id}
                      className="flex gap-3 rounded px-2 py-4 transition-all"
                      style={{ marginBottom: '16px', marginTop: '16px' }}
                    >
                      <Avatar className="mt-1 h-8 w-8">
                        <AvatarFallback>
                          {c.author
                            .split(' ')
                            .map((n) => n[0])
                            .join('')
                            .slice(0, 2)}
                        </AvatarFallback>
                      </Avatar>
                      <div className="flex-1">
                        <div className="mb-1 flex items-center gap-2 text-xs text-muted-foreground">
                          <span className="font-medium text-foreground">{c.author}</span>
                          <span>•</span>
                          <span>{formatDate(c.date)}</span>
                        </div>
                        <p className="text-sm leading-relaxed">{c.text}</p>
                      </div>
                    </div>
                  ))}
                  <Separator />
                  <div className="flex items-start gap-2">
                    <Textarea
                      placeholder="Comments editing coming later ..."
                      className="min-h-[80px]"
                      value={newComment}
                      onChange={(e) => setNewComment(e.target.value)}
                      readOnly
                    />
                    <Button onClick={addComment} className="shrink-0" disabled>
                      Post
                    </Button>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Comments are out of scope for this v1 metadata editor.
                  </p>
                </div>
              </div>
            </div>

            <div className="hidden xl:block">
              <div className="sticky top-6">
                <SimulationSummaryRail
                  summary={summary}
                  summaryLoading={summaryLoading}
                  summaryError={summaryError}
                  summaryRequested={summaryRequested}
                  summaryElapsedMs={summaryElapsedMs}
                  summaryLastDurationMs={summaryLastDurationMs}
                  onGenerateSummary={onGenerateSummary}
                  canGenerateSummary={canGenerateSummary}
                  llmSummaryAvailable={llmSummaryAvailable}
                  autoGenerateDeterministicOnLoad={autoGenerateDeterministicOnLoad}
                  showLoginForAiSummary={showLoginForAiSummary}
                  isCheckingAuth={isCheckingAuth}
                  onLoginForSummary={onLoginForSummary}
                />
              </div>
            </div>
          </div>
        </TabsContent>

        {/* OUTPUTS TAB */}
        <TabsContent value="outputs" className="space-y-6">
          {isEditing ? (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">Artifacts</CardTitle>
              </CardHeader>
              <CardContent>
                <EditableResourceList
                  title="Saved Artifacts"
                  description="Manage output, archive, run script, and post-processing artifact paths or URIs."
                  items={artifactRows}
                  kindOptions={ARTIFACT_KIND_OPTIONS}
                  valueLabel="Path or URI"
                  valuePlaceholder="/path/to/resource or s3://bucket/object"
                  addLabel="Add artifact"
                  onAdd={addArtifactRow}
                  onKindChange={(index, kind) => updateArtifactRow(index, { kind })}
                  onLabelChange={(index, value) => updateArtifactRow(index, { label: value })}
                  onValueChange={(index, value) => updateArtifactRow(index, { value })}
                  onRemove={removeArtifactRow}
                  rowErrors={combinedRowErrors.artifacts}
                />
              </CardContent>
            </Card>
          ) : (
            <>
              <SimulationPathCard
                kind="output"
                title="Output Paths"
                description="These are the primary output files generated by the simulation."
                paths={outputArtifacts}
                emptyText="No output paths available."
              />
              <SimulationPathCard
                kind="archive"
                title="Archive Paths"
                description="These paths contain archived data files from the simulation."
                paths={archiveArtifacts}
                emptyText="No archive artifacts available."
              />
              <SimulationPathCard
                kind="run_script"
                title="Run Script Paths"
                description="Scripts used to run the simulation."
                paths={runScriptArtifacts}
                emptyText="No run script artifacts available."
              />
              <SimulationPathCard
                kind="postprocessing_script"
                title="Post-processing Script Paths"
                description="Scripts used after the main run to transform or analyze outputs."
                paths={postprocessingScriptArtifacts}
                emptyText="No post-processing script artifacts available."
              />
            </>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
};
