import { TooltipTrigger } from '@radix-ui/react-tooltip';
import { Archive, ClipboardList, FileText, Info, Link2, Package } from 'lucide-react';
import React, { JSX } from 'react';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tooltip, TooltipContent, TooltipProvider } from '@/components/ui/tooltip';

interface SimulationPathCard {
  kind: string;
  title: string;
  description?: string;
  paths?: string[] | { url: string; label: string }[];
  emptyText: string;
}

const titleIconMap: Record<string, JSX.Element> = {
  output: <Package size={16} />,
  archive: <Archive size={16} />,
  runScript: <FileText size={16} />,
  batchLog: <ClipboardList size={16} />,
};

export const SimulationPathCard = ({
  kind,
  title,
  paths,
  emptyText,
  description,
}: SimulationPathCard) => {
  const hasPaths = paths && paths.length > 0;

  return (
    <Card
      className={
        hasPaths
          ? 'transition-colors hover:bg-accent/5'
          : 'bg-muted/40 border-dashed opacity-90 hover:opacity-100 transition-all hover:bg-accent/5'
      }
    >
      <CardHeader className="pb-2">
        <CardTitle
          className={`text-base flex items-center gap-2 ${hasPaths ? '' : 'text-muted-foreground'}`}
        >
          {React.cloneElement(titleIconMap[kind] || <></>, { size: 20 })}
          {title}
          {description && (
            <TooltipProvider delayDuration={100}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span
                    className="cursor-help text-muted-foreground align-middle"
                    title={description}
                  >
                    <Info size={14} strokeWidth={1.5} />
                  </span>
                </TooltipTrigger>
                <TooltipContent>{description}</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          )}
        </CardTitle>
      </CardHeader>

      <CardContent className="space-y-2 text-sm">
        {hasPaths ? (
          <ul className="list-disc pl-5">
            {paths.map((path) => {
              const url = typeof path === 'string' ? path : path.url;
              const label = typeof path === 'string' ? path : path.label;
              return (
                <li key={url || label} className="flex items-center gap-2">
                  <a
                    className="text-blue-600 hover:underline flex items-center gap-1"
                    href={url}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <Link2 size={16} className="inline-block" />
                    {label}
                  </a>
                </li>
              );
            })}
          </ul>
        ) : (
          <p className="text-muted-foreground italic flex items-center gap-1">
            {emptyText}
            <TooltipProvider delayDuration={100}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Info size={14} strokeWidth={1.5} className="inline cursor-help align-middle" />
                </TooltipTrigger>
                <TooltipContent>
                  These files will be listed here if they are generated by the simulation or added
                  manually.
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </p>
        )}
      </CardContent>
    </Card>
  );
};
