import { ArrowLeft, ChevronDown, CircleHelp } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

import { SimulationStatusBadge } from '@/components/shared/SimulationStatusBadge';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { Spinner } from '@/components/ui/spinner';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { SimulationPathCard } from '@/features/simulations/components/SimulationPathCard';
import {
  SimulationSummaryLauncher,
  SimulationSummaryRail,
} from '@/features/simulations/components/SimulationSummaryPanel';
import { SimulationTypeBadge } from '@/features/simulations/components/SimulationTypeBadge';
import { cn } from '@/lib/utils';
import type { SimulationOut, SimulationSummaryResponseOut, SimulationUpdate } from '@/types';
import { getArtifactsByKind } from '@/types/artifact';
import { formatDate, getSimulationDuration } from '@/utils/utils';

// -------------------- Types --------------------
interface SimulationDetailsViewProps {
  simulation: SimulationOut;
  isCompareSelected?: boolean;
  compareSelectionCount?: number;
  maxCompareSelection?: number;
  canEdit?: boolean;
  isSaving?: boolean;
  saveError?: string | null;
  backHref?: string;
  backLabel?: string;
  paceLink?: {
    href: string;
    label: string;
  } | null;
  onToggleCompare?: () => void;
  onSave?: (payload: SimulationUpdate) => Promise<boolean> | boolean;
  onClearSaveError?: () => void;
  isResolvingPace?: boolean;
  showPaceFallbackInfo?: boolean;
  summary?: SimulationSummaryResponseOut | null;
  summaryLoading?: boolean;
  summaryError?: string | null;
  summaryRequested?: boolean;
  summaryElapsedMs?: number;
  summaryLastDurationMs?: number | null;
  onGenerateSummary?: () => void | Promise<void>;
  canGenerateSummary?: boolean;
  llmSummaryAvailable?: boolean;
  autoGenerateDeterministicOnLoad?: boolean;
  showLoginForAiSummary?: boolean;
  isCheckingAuth?: boolean;
  onLoginForSummary?: () => void;
}

// -------------------- Small UI helpers --------------------
const FieldRow = ({ label, children }: { label: string; children: React.ReactNode }) => (
  <div className="grid grid-cols-12 items-center gap-2">
    <Label className="col-span-3 md:col-span-2 text-xs text-muted-foreground">{label}</Label>
    <div className="col-span-9 min-w-0 md:col-span-10">{children}</div>
  </div>
);

const ReadonlyInput = ({ value, className }: { value?: string | null; className?: string }) => (
  <div
    className={cn(
      'flex min-h-8 min-w-0 items-center truncate rounded-md border border-border/60 bg-muted/35 px-3 py-1.5 text-sm text-foreground/90',
      className,
    )}
    title={value ?? undefined}
  >
    {value || '—'}
  </div>
);

const ReadonlyText = ({ value, className }: { value?: string | null; className?: string }) => (
  <p className={cn('min-w-0 truncate text-sm text-foreground/90', className)} title={value ?? undefined}>
    {value || '—'}
  </p>
);

const UserDisplay = ({
  user,
  fallbackId,
}: {
  user?: { full_name?: string | null; email: string } | null;
  fallbackId?: string | null;
}) => {
  if (user) return <span className="text-sm">by {user.full_name ?? user.email}</span>;
  if (fallbackId) return <span className="text-sm">by {fallbackId}</span>;
  return null;
};

const ReadonlyTextBlock = ({ value, className }: { value?: string | null; className?: string }) => (
  <div
    className={cn(
      'min-h-[80px] whitespace-pre-wrap rounded-md border bg-muted/30 px-3 py-2 text-sm break-words',
      className,
    )}
  >
    {value?.trim() ? value : '—'}
  </div>
);

const EDITABLE_FIELDS = [
  'description',
  'campaign',
  'experimentType',
  'compiler',
  'hpcUsername',
  'keyFeatures',
  'knownIssues',
  'notesMarkdown',
  'gitRepositoryUrl',
  'gitBranch',
  'gitTag',
  'gitCommitHash',
] as const;

type EditableField = (typeof EDITABLE_FIELDS)[number];
type EditableFormState = Record<EditableField, string>;

const SINGLE_LINE_FIELDS: ReadonlySet<EditableField> = new Set([
  'campaign',
  'experimentType',
  'compiler',
  'hpcUsername',
  'gitRepositoryUrl',
  'gitBranch',
  'gitTag',
  'gitCommitHash',
]);

const toEditableFormState = (simulation: SimulationOut): EditableFormState => ({
  description: simulation.description ?? '',
  campaign: simulation.campaign ?? '',
  experimentType: simulation.experimentType ?? '',
  compiler: simulation.compiler ?? '',
  hpcUsername: simulation.hpcUsername ?? '',
  keyFeatures: simulation.keyFeatures ?? '',
  knownIssues: simulation.knownIssues ?? '',
  notesMarkdown: simulation.notesMarkdown ?? '',
  gitRepositoryUrl: simulation.gitRepositoryUrl ?? '',
  gitBranch: simulation.gitBranch ?? '',
  gitTag: simulation.gitTag ?? '',
  gitCommitHash: simulation.gitCommitHash ?? '',
});

const normalizeEditableValue = (field: EditableField, value: string): string | null => {
  const trimmed = value.trim();

  if (!trimmed) {
    return null;
  }

  return SINGLE_LINE_FIELDS.has(field) ? trimmed : value;
};

const buildUpdatePayload = (
  simulation: SimulationOut,
  formState: EditableFormState,
): SimulationUpdate => {
  const payload: SimulationUpdate = {};

  for (const field of EDITABLE_FIELDS) {
    const nextValue = normalizeEditableValue(field, formState[field]);
    const currentValue = simulation[field] ?? null;

    if (nextValue !== currentValue) {
      payload[field] = nextValue;
    }
  }

  return payload;
};

// -------------------- View Component --------------------
export const SimulationDetailsView = ({
  simulation,
  isCompareSelected = false,
  compareSelectionCount: compareSelectionCountProp = 0,
  maxCompareSelection: maxCompareSelectionProp = 5,
  canEdit = false,
  isSaving = false,
  saveError = null,
  backHref = '/browse',
  backLabel = 'Back to Runs',
  paceLink = null,
  onToggleCompare,
  onSave,
  onClearSaveError,
  isResolvingPace = false,
  showPaceFallbackInfo = false,
  summary = null,
  summaryLoading = false,
  summaryError = null,
  summaryRequested = false,
  summaryElapsedMs = 0,
  summaryLastDurationMs = null,
  onGenerateSummary,
  canGenerateSummary = false,
  llmSummaryAvailable = false,
  autoGenerateDeterministicOnLoad = false,
  showLoginForAiSummary = false,
  isCheckingAuth = false,
  onLoginForSummary,
}: SimulationDetailsViewProps) => {
  const [activeTab, setActiveTab] = useState('summary');
  const [isEditing, setIsEditing] = useState(false);
  const [isAdvancedMetadataOpen, setIsAdvancedMetadataOpen] = useState(false);
  const [formState, setFormState] = useState<EditableFormState>(() =>
    toEditableFormState(simulation),
  );
  const performanceLinks = simulation.groupedLinks.performance ?? [];
  const outputArtifacts = getArtifactsByKind(
    simulation.artifacts,
    simulation.groupedArtifacts,
    'output',
  ).map((artifact) => ({
    url: artifact.uri,
    label: artifact.label?.trim() || artifact.uri,
  }));
  const archiveArtifacts = getArtifactsByKind(
    simulation.artifacts,
    simulation.groupedArtifacts,
    'archive',
  ).map((artifact) => ({
    url: artifact.uri,
    label: artifact.label?.trim() || artifact.uri,
  }));
  const runScriptArtifacts = getArtifactsByKind(
    simulation.artifacts,
    simulation.groupedArtifacts,
    'run_script',
  ).map((artifact) => ({
    url: artifact.uri,
    label: artifact.label?.trim() || artifact.uri,
  }));
  const postprocessingScriptArtifacts = getArtifactsByKind(
    simulation.artifacts,
    simulation.groupedArtifacts,
    'postprocessing_script',
  ).map((artifact) => ({
    url: artifact.uri,
    label: artifact.label?.trim() || artifact.uri,
  }));

  // Temporary local-only comments
  const [newComment, setNewComment] = useState('');
  const [comments, setComments] = useState<
    { id: string; author: string; date: string; text: string }[]
  >([
    {
      id: 'c1',
      author: 'Jane Doe',
      date: '2024-02-15T13:45:00Z',
      text: 'The sea-ice diagnostics will be added later.',
    },
    ]);

  useEffect(() => {
    setFormState(toEditableFormState(simulation));
    setIsEditing(false);
  }, [simulation]);

  useEffect(() => {
    if (!canEdit) {
      setFormState(toEditableFormState(simulation));
      setIsEditing(false);
    }
  }, [canEdit, simulation]);

  const updateField = (field: EditableField, value: string) => {
    onClearSaveError?.();
    setFormState((current) => ({
      ...current,
      [field]: value,
    }));
  };

  const handleCancelEdit = () => {
    onClearSaveError?.();
    setFormState(toEditableFormState(simulation));
    setIsEditing(false);
  };

  const handleSave = async () => {
    if (!onSave) return;

    const payload = buildUpdatePayload(simulation, formState);

    if (Object.keys(payload).length === 0) {
      onClearSaveError?.();
      setIsEditing(false);
      return;
    }

    const saved = await onSave(payload);

    if (saved) {
      setIsEditing(false);
    }
  };

  const hasUnsavedChanges = Object.keys(buildUpdatePayload(simulation, formState)).length > 0;
  const compareSelectionCount = compareSelectionCountProp ?? 0;
  const maxCompareSelection = maxCompareSelectionProp ?? 5;
  const isCompareActionDisabled =
    !isCompareSelected && compareSelectionCount >= maxCompareSelection;
  const compareActionLabel = isCompareSelected
    ? 'Remove from Comparison'
    : 'Add to Comparison';
  const compareActionTooltip = isCompareActionDisabled
    ? `Compare list is full. Remove one of the ${maxCompareSelection} selected runs first.`
    : undefined;

  const addComment = () => {
    if (!newComment.trim()) return;
    setComments((prev) => [
      ...prev,
      {
        id: `c${prev.length + 1}`,
        author: 'You',
        date: new Date().toISOString(),
        text: newComment.trim(),
      },
    ]);
    setNewComment('');
  };

  return (
    <div className="mx-auto w-full max-w-[1400px] space-y-6 px-6 py-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <Button variant="outline" size="sm" asChild className="mb-3">
            <Link to={backHref}>
              <ArrowLeft className="h-4 w-4" />
              {backLabel}
            </Link>
          </Button>
          <h1 className="text-2xl font-bold">{simulation.executionId}</h1>
          <p className="text-sm text-muted-foreground">{simulation.caseName}</p>
          <div className="mt-1 flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
            <span>Type:</span>
            <SimulationTypeBadge simulationType={simulation.simulationType} />
            <span>•</span>
            <span>Status:</span>
            <SimulationStatusBadge status={simulation.status} />
            {simulation.gitTag && (
              <>
                <span>•</span>
                <span>Version/Tag:</span>
                <code className="rounded bg-muted px-2 py-0.5 text-xs">{simulation.gitTag}</code>
              </>
            )}
          </div>
        </div>
        <div className="flex items-center gap-2">
          {compareActionTooltip ? (
            <TooltipProvider delayDuration={150}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span tabIndex={0}>
                    <Button variant="outline" onClick={onToggleCompare} disabled={isCompareActionDisabled}>
                      {compareActionLabel}
                    </Button>
                  </span>
                </TooltipTrigger>
                <TooltipContent>{compareActionTooltip}</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ) : (
            <Button variant="outline" onClick={onToggleCompare}>
              {compareActionLabel}
            </Button>
          )}
          {!isEditing &&
            (canEdit ? (
              <Button onClick={() => setIsEditing(true)}>Edit</Button>
            ) : (
              <TooltipProvider delayDuration={150}>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span tabIndex={0}>
                      <Button disabled>Edit</Button>
                    </span>
                  </TooltipTrigger>
                  <TooltipContent>Login required</TooltipContent>
                </Tooltip>
              </TooltipProvider>
            ))}
          {canEdit && isEditing && (
            <>
              <Button variant="outline" onClick={handleCancelEdit} disabled={isSaving}>
                Cancel
              </Button>
              <Button onClick={handleSave} disabled={isSaving || !hasUnsavedChanges}>
                {isSaving ? 'Saving…' : 'Save Changes'}
              </Button>
            </>
          )}
        </div>
      </div>
      {isEditing && saveError && <div className="text-sm text-red-600">{saveError}</div>}

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="w-full justify-start overflow-x-auto">
          <TabsTrigger value="summary">Summary</TabsTrigger>
          <TabsTrigger value="outputs">Outputs & Logs</TabsTrigger>
        </TabsList>

        {/* SUMMARY TAB */}
        <TabsContent value="summary" className="space-y-6">
          <div className="xl:hidden">
            <SimulationSummaryLauncher
              summary={summary}
              summaryLoading={summaryLoading}
              summaryError={summaryError}
              summaryRequested={summaryRequested}
              summaryElapsedMs={summaryElapsedMs}
              summaryLastDurationMs={summaryLastDurationMs}
              onGenerateSummary={onGenerateSummary}
              canGenerateSummary={canGenerateSummary}
              llmSummaryAvailable={llmSummaryAvailable}
              autoGenerateDeterministicOnLoad={autoGenerateDeterministicOnLoad}
              showLoginForAiSummary={showLoginForAiSummary}
              isCheckingAuth={isCheckingAuth}
              onLoginForSummary={onLoginForSummary}
            />
          </div>

          <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px] xl:items-start">
            <div className="space-y-6">
              <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Configuration</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <FieldRow label="Case Name">
                      <ReadonlyInput value={simulation.caseName} />
                    </FieldRow>
                    {simulation.caseGroup && (
                      <FieldRow label="Case Group">
                        <ReadonlyInput value={simulation.caseGroup} />
                      </FieldRow>
                    )}
                    <FieldRow label="Case Hash">
                      <ReadonlyInput value={simulation.caseHash ?? undefined} className="font-mono" />
                    </FieldRow>
                    <FieldRow label="Model Version">
                      <ReadonlyInput value={simulation.gitTag ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Compset">
                      <ReadonlyInput value={simulation.compset ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Compset Alias">
                      <ReadonlyInput value={simulation.compsetAlias ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Grid Name">
                      <ReadonlyInput value={simulation.gridName ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Grid Resolution">
                      <ReadonlyInput value={simulation.gridResolution ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Initialization Type">
                      <ReadonlyInput value={simulation.initializationType ?? undefined} />
                    </FieldRow>
                    <FieldRow label="Compiler">
                      {isEditing ? (
                        <Input
                          value={formState.compiler}
                          onChange={(event) => updateField('compiler', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyInput value={simulation.compiler ?? undefined} />
                      )}
                    </FieldRow>
                    {(isEditing || simulation.description) && (
                      <div className="pt-2">
                        <Label className="mb-1 block text-xs text-muted-foreground">
                          Description
                        </Label>
                        {isEditing ? (
                          <Textarea
                            value={formState.description}
                            onChange={(event) => updateField('description', event.target.value)}
                            className="min-h-[120px]"
                          />
                        ) : (
                          <ReadonlyTextBlock value={simulation.description} />
                        )}
                      </div>
                    )}
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Model Setup</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-3">
                    <FieldRow label="Simulation Type">
                      <ReadonlyInput value={simulation.simulationType} />
                    </FieldRow>
                    <FieldRow label="Status">
                      <ReadonlyInput value={simulation.status} />
                    </FieldRow>
                    <FieldRow label="Campaign ID">
                      {isEditing ? (
                        <Input
                          value={formState.campaign}
                          onChange={(event) => updateField('campaign', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyInput value={simulation.campaign} />
                      )}
                    </FieldRow>
                    <FieldRow label="Experiment Type ID">
                      {isEditing ? (
                        <Input
                          value={formState.experimentType}
                          onChange={(event) => updateField('experimentType', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyInput value={simulation.experimentType} />
                      )}
                    </FieldRow>
                    <FieldRow label="Machine">
                      <ReadonlyInput value={simulation.machine.name} />
                    </FieldRow>
                  </CardContent>
                </Card>
              </div>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-base">Compare Setup</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <p className="text-sm text-muted-foreground">
                    Use case details to select runs from one Case Hash subgroup, then open compare
                    for side-by-side review.
                  </p>
                  <Button variant="outline" asChild>
                    <Link to={`/cases/${simulation.caseId}`}>Open Case Details</Link>
                  </Button>
                </CardContent>
              </Card>

              <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Timeline</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2">
                    <FieldRow label="Simulation Start Date">
                      <span className="text-sm">
                        {simulation.simulationStartDate
                          ? formatDate(simulation.simulationStartDate)
                          : '—'}
                      </span>
                    </FieldRow>
                    <FieldRow label="Simulation End Date">
                      <span className="text-sm">
                        {simulation.simulationEndDate
                          ? formatDate(simulation.simulationEndDate)
                          : '—'}
                      </span>
                    </FieldRow>
                    <FieldRow label="Total Duration">
                      <span className="text-sm">
                        {simulation.simulationStartDate && simulation.simulationEndDate
                          ? getSimulationDuration(
                              simulation.simulationStartDate,
                              simulation.simulationEndDate,
                            )
                          : '—'}
                      </span>
                    </FieldRow>
                    {simulation.runStartDate && (
                      <FieldRow label="Run Start Date">
                        <span className="text-sm">{formatDate(simulation.runStartDate)}</span>
                      </FieldRow>
                    )}
                    {simulation.runEndDate && (
                      <FieldRow label="Run End Date">
                        <span className="text-sm">{formatDate(simulation.runEndDate)}</span>
                      </FieldRow>
                    )}
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Provenance</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2">
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Created:
                      </Label>
                      <span className="text-sm">
                        {simulation.createdAt ? formatDate(simulation.createdAt) : '—'}
                      </span>
                      <UserDisplay
                        user={simulation.createdByUser}
                        fallbackId={simulation.createdBy}
                      />
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Last edited:
                      </Label>
                      <span className="text-sm">
                        {simulation.updatedAt ? formatDate(simulation.updatedAt) : '—'}
                      </span>
                      <UserDisplay
                        user={simulation.lastUpdatedByUser}
                        fallbackId={simulation.lastUpdatedBy}
                      />
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Simulation UUID:
                      </Label>
                      <ReadonlyInput value={simulation.id} />
                      {simulation.id && (
                        <Button
                          variant="outline"
                          size="sm"
                          type="button"
                          onClick={() => navigator.clipboard.writeText(simulation.id)}
                          title="Copy full Simulation ID"
                        >
                          Copy
                        </Button>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Case ID:
                      </Label>
                      <ReadonlyInput value={simulation.caseId} />
                      {simulation.caseId && (
                        <Button
                          variant="outline"
                          size="sm"
                          type="button"
                          onClick={() => navigator.clipboard.writeText(simulation.caseId)}
                          title="Copy full Case ID"
                        >
                          Copy
                        </Button>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Machine ID:
                      </Label>
                      <ReadonlyInput value={simulation.machineId} />
                      {simulation.machineId && (
                        <Button
                          variant="outline"
                          size="sm"
                          type="button"
                          onClick={() => navigator.clipboard.writeText(simulation.machineId)}
                          title="Copy full Machine ID"
                        >
                          Copy
                        </Button>
                      )}
                    </div>

                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Git Repository:
                      </Label>
                      {isEditing ? (
                        <Input
                          type="url"
                          value={formState.gitRepositoryUrl}
                          onChange={(event) => updateField('gitRepositoryUrl', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <>
                          {simulation.gitRepositoryUrl ? (
                            <a
                              href={simulation.gitRepositoryUrl}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="block min-w-0 truncate text-sm text-blue-600 hover:underline"
                              title={simulation.gitRepositoryUrl}
                            >
                              {simulation.gitRepositoryUrl}
                            </a>
                          ) : (
                            <p className="text-sm">—</p>
                          )}
                        </>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Git Branch:
                      </Label>
                      {isEditing ? (
                        <Input
                          value={formState.gitBranch}
                          onChange={(event) => updateField('gitBranch', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyText value={simulation.gitBranch} />
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Git Tag:
                      </Label>
                      {isEditing ? (
                        <Input
                          value={formState.gitTag}
                          onChange={(event) => updateField('gitTag', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyText value={simulation.gitTag} />
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        Git Commit Hash:
                      </Label>
                      {isEditing ? (
                        <Input
                          value={formState.gitCommitHash}
                          onChange={(event) => updateField('gitCommitHash', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyText value={simulation.gitCommitHash} />
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <Label className="min-w-[100px] text-xs text-muted-foreground">
                        HPC Username:
                      </Label>
                      {isEditing ? (
                        <Input
                          value={formState.hpcUsername}
                          onChange={(event) => updateField('hpcUsername', event.target.value)}
                          className="h-8 text-sm"
                        />
                      ) : (
                        <ReadonlyText value={simulation.hpcUsername} />
                      )}
                    </div>
                  </CardContent>
                </Card>
              </div>

              {(isEditing || simulation.keyFeatures || simulation.knownIssues) && (
                <Card>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">Scientific Metadata</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {(isEditing || simulation.keyFeatures) && (
                      <div>
                        <Label className="mb-1 block text-xs text-muted-foreground">
                          Key Features
                        </Label>
                        {isEditing ? (
                          <Textarea
                            value={formState.keyFeatures}
                            onChange={(event) => updateField('keyFeatures', event.target.value)}
                            className="min-h-[120px]"
                          />
                        ) : (
                          <ReadonlyTextBlock value={simulation.keyFeatures} />
                        )}
                      </div>
                    )}
                    {(isEditing || simulation.knownIssues) && (
                      <div>
                        <Label className="mb-1 block text-xs text-muted-foreground">
                          Known Issues
                        </Label>
                        {isEditing ? (
                          <Textarea
                            value={formState.knownIssues}
                            onChange={(event) => updateField('knownIssues', event.target.value)}
                            className="min-h-[120px]"
                          />
                        ) : (
                          <ReadonlyTextBlock value={simulation.knownIssues} />
                        )}
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

              {simulation.extra && Object.keys(simulation.extra).length > 0 && (
                <Collapsible open={isAdvancedMetadataOpen} onOpenChange={setIsAdvancedMetadataOpen}>
                  <Card>
                    <CardHeader className="pb-2">
                      <CollapsibleTrigger className="flex w-full items-center justify-between [&[data-state=open]>svg]:rotate-180">
                        <CardTitle className="text-base">Advanced Metadata</CardTitle>
                        <ChevronDown className="h-4 w-4 text-muted-foreground transition-transform duration-200" />
                      </CollapsibleTrigger>
                    </CardHeader>
                    <CollapsibleContent>
                      <CardContent>
                        {isAdvancedMetadataOpen && (
                          <pre className="max-h-[400px] overflow-auto rounded-md bg-muted p-4 text-xs">
                            {JSON.stringify(simulation.extra, null, 2)}
                          </pre>
                        )}
                      </CardContent>
                    </CollapsibleContent>
                  </Card>
                </Collapsible>
              )}

              <Card>
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-base">External Resources</CardTitle>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
                    <div>
                      <Label className="mb-1 block text-sm">Diagnostics</Label>
                      {simulation.groupedLinks.diagnostic?.length ? (
                        <ul className="list-disc pl-5 text-sm">
                          {simulation.groupedLinks.diagnostic.map((d) => (
                            <li key={d.url} className="flex items-center gap-2">
                              <a
                                className="flex items-center gap-1 text-blue-600 hover:underline"
                                href={d.url}
                                target="_blank"
                                rel="noreferrer"
                              >
                                <svg
                                  xmlns="http://www.w3.org/2000/svg"
                                  width="16"
                                  height="16"
                                  fill="none"
                                  viewBox="0 0 24 24"
                                  stroke="currentColor"
                                  className="inline-block"
                                >
                                  <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth={2}
                                    d="M15 7h2a5 5 0 015 5v0a5 5 0 01-5 5h-2m-6 0H7a5 5 0 01-5-5v0a5 5 0 015-5h2m1 5h4"
                                  />
                                </svg>
                                {d.label}
                              </a>
                            </li>
                          ))}
                        </ul>
                      ) : (
                        <div className="mb-2 text-sm text-muted-foreground">
                          Links to diagnostics will appear here once available.
                        </div>
                      )}
                    </div>
                    <div>
                      <Label className="mb-1 block text-sm">Performance</Label>
                      {performanceLinks.length || paceLink ? (
                        <ul className="list-disc pl-5 text-sm">
                          {performanceLinks.map((p) => (
                            <li key={p.url} className="flex items-center gap-2">
                              <a
                                className="flex items-center gap-1 text-blue-600 hover:underline"
                                href={p.url}
                                target="_blank"
                                rel="noreferrer"
                              >
                                <svg
                                  xmlns="http://www.w3.org/2000/svg"
                                  width="16"
                                  height="16"
                                  fill="none"
                                  viewBox="0 0 24 24"
                                  stroke="currentColor"
                                  className="inline-block"
                                >
                                  <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth={2}
                                    d="M15 7h2a5 5 0 015 5v0a5 5 0 01-5 5h-2m-6 0H7a5 5 0 01-5-5v0a5 5 0 015-5h2m1 5h4"
                                  />
                                </svg>
                                {p.label}
                              </a>
                            </li>
                          ))}
                          {paceLink && (
                            <li className="flex items-center gap-2">
                              <a
                                className="flex items-center gap-1 text-blue-600 hover:underline"
                                href={paceLink.href}
                                target="_blank"
                                rel="noreferrer"
                              >
                                <svg
                                  xmlns="http://www.w3.org/2000/svg"
                                  width="16"
                                  height="16"
                                  fill="none"
                                  viewBox="0 0 24 24"
                                  stroke="currentColor"
                                  className="inline-block"
                                >
                                  <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    strokeWidth={2}
                                    d="M15 7h2a5 5 0 015 5v0a5 5 0 01-5 5h-2m-6 0H7a5 5 0 01-5-5v0a5 5 0 015-5h2m1 5h4"
                                  />
                                </svg>
                                {paceLink.label}
                              </a>
                              {isResolvingPace && (
                                <>
                                  <Spinner className="size-3 text-muted-foreground" />
                                  <TooltipProvider delayDuration={150}>
                                    <Tooltip>
                                      <TooltipTrigger asChild>
                                        <button
                                          type="button"
                                          aria-label="PACE link resolution status"
                                          className="text-muted-foreground hover:text-foreground"
                                        >
                                          <CircleHelp className="size-3" />
                                        </button>
                                      </TooltipTrigger>
                                      <TooltipContent>
                                        Checking for a direct PACE experiment link
                                      </TooltipContent>
                                    </Tooltip>
                                  </TooltipProvider>
                                </>
                              )}
                              {!isResolvingPace && showPaceFallbackInfo && (
                                <TooltipProvider delayDuration={150}>
                                  <Tooltip>
                                    <TooltipTrigger asChild>
                                      <button
                                        type="button"
                                        aria-label="PACE link fallback information"
                                        className="text-muted-foreground hover:text-foreground"
                                      >
                                        <CircleHelp className="size-3" />
                                      </button>
                                    </TooltipTrigger>
                                    <TooltipContent>
                                      Direct PACE experiment link not found. Search results may
                                      still contain this run.
                                    </TooltipContent>
                                  </Tooltip>
                                </TooltipProvider>
                              )}
                            </li>
                          )}
                        </ul>
                      ) : (
                        <div className="mb-2 text-sm text-muted-foreground">
                          Links to performance metrics will appear here once available.
                        </div>
                      )}
                    </div>
                  </div>
                  <div>
                    {Object.entries(simulation.groupedLinks)
                      .filter(([key]) => key !== 'diagnostic' && key !== 'performance')
                      .map(([key, linkList]) => (
                        <div key={key} className="mb-4">
                          <h4 className="text-sm font-medium capitalize">{key}</h4>
                          <ul className="list-disc pl-5 text-sm">
                            {linkList.map((link) => (
                              <li key={link.url} className="flex items-center gap-2">
                                <a
                                  className="flex items-center gap-1 text-blue-600 hover:underline"
                                  href={link.url}
                                  target="_blank"
                                  rel="noreferrer"
                                >
                                  <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    width="16"
                                    height="16"
                                    fill="none"
                                    viewBox="0 0 24 24"
                                    stroke="currentColor"
                                    className="inline-block"
                                  >
                                    <path
                                      strokeLinecap="round"
                                      strokeLinejoin="round"
                                      strokeWidth={2}
                                      d="M15 7h2a5 5 0 015 5v0a5 5 0 01-5 5h-2m-6 0H7a5 5 0 01-5-5v0a5 5 0 015-5h2m1 5h4"
                                    />
                                  </svg>
                                  {link.label}
                                </a>
                              </li>
                            ))}
                          </ul>
                        </div>
                      ))}
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-base">Notes</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {isEditing ? (
                    <Textarea
                      placeholder="Add notes..."
                      value={formState.notesMarkdown}
                      onChange={(event) => updateField('notesMarkdown', event.target.value)}
                      className="min-h-[160px]"
                    />
                  ) : (
                    <ReadonlyTextBlock value={simulation.notesMarkdown} className="min-h-[160px]" />
                  )}
                  {!canEdit && (
                    <p className="text-xs text-muted-foreground">
                      Log in to edit simulation metadata. This page stays read-only when signed out.
                    </p>
                  )}
                  {canEdit && isEditing && (
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-xs text-muted-foreground">
                        Save updates description, provenance, and notes fields only.
                      </div>
                      <div className="flex items-center gap-2">
                        <Button variant="outline" onClick={handleCancelEdit} disabled={isSaving}>
                          Cancel
                        </Button>
                        <Button onClick={handleSave} disabled={isSaving || !hasUnsavedChanges}>
                          {isSaving ? 'Saving…' : 'Save Changes'}
                        </Button>
                      </div>
                    </div>
                  )}
                  {isEditing && saveError && <p className="text-sm text-red-600">{saveError}</p>}
                </CardContent>
              </Card>

              <div>
                <h3 className="mb-2 text-sm font-semibold tracking-tight">Comments</h3>
                <div className="space-y-4">
                  {comments.map((c) => (
                    <div
                      key={c.id}
                      className="flex gap-3 rounded px-2 py-4 transition-all"
                      style={{ marginBottom: '16px', marginTop: '16px' }}
                    >
                      <Avatar className="mt-1 h-8 w-8">
                        <AvatarFallback>
                          {c.author
                            .split(' ')
                            .map((n) => n[0])
                            .join('')
                            .slice(0, 2)}
                        </AvatarFallback>
                      </Avatar>
                      <div className="flex-1">
                        <div className="mb-1 flex items-center gap-2 text-xs text-muted-foreground">
                          <span className="font-medium text-foreground">{c.author}</span>
                          <span>•</span>
                          <span>{formatDate(c.date)}</span>
                        </div>
                        <p className="text-sm leading-relaxed">{c.text}</p>
                      </div>
                    </div>
                  ))}
                  <Separator />
                  <div className="flex items-start gap-2">
                    <Textarea
                      placeholder="Comments editing coming later ..."
                      className="min-h-[80px]"
                      value={newComment}
                      onChange={(e) => setNewComment(e.target.value)}
                      readOnly
                    />
                    <Button onClick={addComment} className="shrink-0" disabled>
                      Post
                    </Button>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Comments are out of scope for this v1 metadata editor.
                  </p>
                </div>
              </div>
            </div>

            <div className="hidden xl:block">
              <div className="sticky top-6">
                <SimulationSummaryRail
                  summary={summary}
                  summaryLoading={summaryLoading}
                  summaryError={summaryError}
                  summaryRequested={summaryRequested}
                  summaryElapsedMs={summaryElapsedMs}
                  summaryLastDurationMs={summaryLastDurationMs}
                  onGenerateSummary={onGenerateSummary}
                  canGenerateSummary={canGenerateSummary}
                  llmSummaryAvailable={llmSummaryAvailable}
                  autoGenerateDeterministicOnLoad={autoGenerateDeterministicOnLoad}
                  showLoginForAiSummary={showLoginForAiSummary}
                  isCheckingAuth={isCheckingAuth}
                  onLoginForSummary={onLoginForSummary}
                />
              </div>
            </div>
          </div>
        </TabsContent>

        {/* OUTPUTS TAB */}
        <TabsContent value="outputs" className="space-y-6">
          <SimulationPathCard
            kind="output"
            title="Output Paths"
            description="These are the primary output files generated by the simulation."
            paths={outputArtifacts}
            emptyText="No output paths available."
          />
          <SimulationPathCard
            kind="archive"
            title="Archive Paths"
            description="These paths contain archived data files from the simulation."
            paths={archiveArtifacts}
            emptyText="No archive artifacts available."
          />
          <SimulationPathCard
            kind="run_script"
            title="Run Script Paths"
            description="Scripts used to run the simulation."
            paths={runScriptArtifacts}
            emptyText="No run script artifacts available."
          />
          <SimulationPathCard
            kind="postprocessing_script"
            title="Post-processing Script Paths"
            description="Scripts used after the main run to transform or analyze outputs."
            paths={postprocessingScriptArtifacts}
            emptyText="No post-processing script artifacts available."
          />
        </TabsContent>
      </Tabs>
    </div>
  );
};
