import axios from 'axios';
import { useEffect, useState } from 'react';
import { useLocation, useParams } from 'react-router-dom';

import { useAuth } from '@/auth/hooks/useAuth';
import { resolvePaceExecution, updateSimulation } from '@/features/simulations/api/api';
import {
  SimulationDetailsView,
  type SimulationSaveError,
} from '@/features/simulations/components/SimulationDetailsView';
import { useSimulation } from '@/features/simulations/hooks/useSimulation';
import { useSimulationSummary } from '@/features/simulations/hooks/useSimulationSummary';
import { toast } from '@/hooks/use-toast';
import type { SimulationOut, SimulationUpdate } from '@/types';

const MAX_COMPARE_SELECTION = 5;

interface SimulationDetailsPageProps {
  selectedSimulationIds: string[];
  setSelectedSimulationIds: (ids: string[]) => void;
}

const getUpdateError = (error: unknown): SimulationSaveError => {
  if (axios.isAxiosError(error)) {
    const detail = error.response?.data?.detail;

    if (typeof detail === 'string') {
      return {
        message: detail,
        validationDetails: [],
      };
    }

    if (Array.isArray(detail)) {
      const validationDetails = detail
        .map((item) => {
          const message = typeof item?.msg === 'string' ? item.msg : null;
          const loc = Array.isArray(item?.loc)
            ? item.loc.filter(
                (part: unknown): part is string | number =>
                  typeof part === 'string' || typeof part === 'number',
              )
            : [];

          if (!message) return null;
          return {
            loc,
            msg: message,
          };
        })
        .filter((item): item is SimulationSaveError['validationDetails'][number] => Boolean(item));

      if (validationDetails.length > 0) {
        return {
          message: 'One or more fields need attention before this simulation can be saved.',
          validationDetails,
        };
      }
    }
  }

  return {
    message: error instanceof Error ? error.message : 'Failed to update simulation.',
    validationDetails: [],
  };
};

export const SimulationDetailsPage = ({
  selectedSimulationIds,
  setSelectedSimulationIds,
}: SimulationDetailsPageProps) => {
  const { id } = useParams<{ id: string }>();
  const location = useLocation();
  const { data: fetchedSimulation, loading, error } = useSimulation(id ?? '');
  const { user, isAuthenticated, loading: authLoading, loginWithGithub } = useAuth();
  const [simulation, setSimulation] = useState<SimulationOut | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [saveError, setSaveError] = useState<SimulationSaveError | null>(null);
  const [paceExperimentId, setPaceExperimentId] = useState<string | null>(null);
  const [isResolvingPace, setIsResolvingPace] = useState(false);
  const [paceResolutionAttempted, setPaceResolutionAttempted] = useState(false);

  const state = location.state as { from?: string } | null;
  const backHref = typeof state?.from === 'string' ? state.from : '/browse';
  const normalizedBackHref = backHref.split(/[?#]/)[0];
  const backLabel = normalizedBackHref.startsWith('/cases/')
    ? 'Back to Case'
    : normalizedBackHref === '/cases'
      ? 'Back to Cases'
      : normalizedBackHref.startsWith('/simulations')
        ? 'Back to Simulations'
        : 'Back to Runs';
  const canEdit = !authLoading && user?.can_edit_managed_content === true;
  const currentSimulation = simulation?.id === id ? simulation : null;
  const executionId = currentSimulation?.executionId?.trim() ?? '';
  const llmSummaryAvailable = currentSimulation?.summaryCapabilities?.llmAvailable ?? false;
  const shouldAutoGenerateSummary =
    currentSimulation?.summaryCapabilities?.autoGenerateDeterministicOnLoad ?? false;
  const showLoginForAiSummary = llmSummaryAvailable && !authLoading && !isAuthenticated;
  const summary = useSimulationSummary(id ?? '', {
    autoGenerate: shouldAutoGenerateSummary,
  });

  useEffect(() => {
    if (fetchedSimulation?.id === id) {
      setSimulation(fetchedSimulation);
      setSaveError(null);
      return;
    }

    if (!loading && !error) {
      setSimulation(null);
    }
  }, [error, fetchedSimulation, id, loading]);

  useEffect(() => {
    if (!executionId) {
      setPaceExperimentId(null);
      setIsResolvingPace(false);
      setPaceResolutionAttempted(false);
      return;
    }

    let cancelled = false;
    setPaceExperimentId(null);
    setIsResolvingPace(true);
    setPaceResolutionAttempted(false);

    resolvePaceExecution(executionId)
      .then((result) => {
        if (!cancelled) {
          setPaceExperimentId(result.experimentId?.trim() || null);
        }
      })
      .catch(() => {
        if (!cancelled) {
          setPaceExperimentId(null);
        }
      })
      .finally(() => {
        if (!cancelled) {
          setIsResolvingPace(false);
          setPaceResolutionAttempted(true);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [executionId]);

  const handleSave = async (payload: SimulationUpdate): Promise<boolean> => {
    if (!id) return false;

    setIsSaving(true);
    setSaveError(null);

    try {
      const updatedSimulation = await updateSimulation(id, payload);
      setSimulation(updatedSimulation);
      return true;
    } catch (saveErr) {
      setSaveError(getUpdateError(saveErr));
      return false;
    } finally {
      setIsSaving(false);
    }
  };

  const handleToggleCompare = () => {
    if (!currentSimulation) return;

    if (selectedSimulationIds.includes(currentSimulation.id)) {
      setSelectedSimulationIds(
        selectedSimulationIds.filter((simulationId) => simulationId !== currentSimulation.id),
      );
      return;
    }

    if (selectedSimulationIds.length >= MAX_COMPARE_SELECTION) {
      toast({
        title: 'Compare list full',
        description: `You can compare up to ${MAX_COMPARE_SELECTION} runs at a time.`,
        variant: 'destructive',
      });
      return;
    }

    setSelectedSimulationIds([...selectedSimulationIds, currentSimulation.id]);
    toast({
      title: 'Added to compare',
      description: `${currentSimulation.executionId} is now in your compare list.`,
    });
  };

  if (!id) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center text-gray-500">Invalid simulation ID</div>
      </div>
    );
  }

  if (loading || (simulation !== null && currentSimulation === null)) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center text-gray-500">Loading simulation details…</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center text-red-600">Error: {error}</div>
      </div>
    );
  }

  if (!currentSimulation) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="text-center text-gray-500">Simulation not found</div>
      </div>
    );
  }

  const paceLink = executionId
    ? paceExperimentId
      ? {
          href: `https://pace.ornl.gov/exp-details/${encodeURIComponent(paceExperimentId)}`,
          label: 'Open in PACE',
        }
      : {
          href: `https://pace.ornl.gov/search/${encodeURIComponent(executionId)}`,
          label: 'Search in PACE',
        }
    : null;

  return (
    <SimulationDetailsView
      simulation={currentSimulation}
      isCompareSelected={selectedSimulationIds.includes(currentSimulation.id)}
      compareSelectionCount={selectedSimulationIds.length}
      maxCompareSelection={MAX_COMPARE_SELECTION}
      backHref={backHref}
      backLabel={backLabel}
      paceLink={paceLink}
      isResolvingPace={isResolvingPace}
      showPaceFallbackInfo={paceResolutionAttempted && !paceExperimentId}
      summary={summary.data}
      summaryLoading={summary.loading}
      summaryError={summary.error}
      summaryRequested={summary.requested}
      summaryElapsedMs={summary.elapsedMs}
      summaryLastDurationMs={summary.lastDurationMs}
      onGenerateSummary={summary.generate}
      canGenerateSummary
      onToggleCompare={handleToggleCompare}
      canEdit={canEdit}
      isAuthenticated={isAuthenticated}
      isSaving={isSaving}
      saveError={saveError}
      onSave={handleSave}
      onClearSaveError={() => setSaveError(null)}
      onLoginToEdit={loginWithGithub}
      llmSummaryAvailable={llmSummaryAvailable}
      autoGenerateDeterministicOnLoad={shouldAutoGenerateSummary}
      showLoginForAiSummary={showLoginForAiSummary}
      isCheckingAuth={authLoading && llmSummaryAvailable}
      onLoginForSummary={loginWithGithub}
    />
  );
};
