"""Remove total_years field from Simulation model and schema

Revision ID: 71f46a7e00a4
Revises: d01eac7d24ce
Create Date: 2025-10-07 13:49:28.037063

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71f46a7e00a4"
down_revision: Union[str, Sequence[str], None] = "d01eac7d24ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulations", "total_years")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulations",
        sa.Column(
            "total_years",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
