"""Remove variable model

Revision ID: d01eac7d24ce
Revises: 3549db208f70
Create Date: 2025-10-07 13:43:39.070068

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d01eac7d24ce"
down_revision: Union[str, Sequence[str], None] = "3549db208f70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simulation_variables")
    op.drop_table("variables")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_variables",
        sa.Column("simulation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "variable_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
            name=op.f("fk_simulation_variables_simulation_id_simulations"),
        ),
        sa.ForeignKeyConstraint(
            ["variable_name"],
            ["variables.name"],
            name=op.f("fk_simulation_variables_variable_name_variables"),
        ),
        sa.PrimaryKeyConstraint(
            "simulation_id", "variable_name", name=op.f("pk_simulation_variables")
        ),
    )
    op.create_table(
        "variables",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=300), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_variables")),
    )
    # ### end Alembic commands ###
